In [10]:
import numpy as np

In [2]:
A = np.diag(np.arange(5)) + np.diag(np.arange(4, 8), k=1) + np.diag(1 + 27*np.ones(4), k=-1)
A

array([[ 0.,  4.,  0.,  0.,  0.],
       [28.,  1.,  5.,  0.,  0.],
       [ 0., 28.,  2.,  6.,  0.],
       [ 0.,  0., 28.,  3.,  7.],
       [ 0.,  0.,  0., 28.,  4.]])

In [5]:
np.shape(A)

(5, 5)

In [31]:
a = np.arange(5)
b = np.arange(6, 11)
a*b

array([ 0,  7, 16, 27, 40])

In [6]:
nz = 10
z = np.linspace(0, 1, nz)
z[2] - z[1]

0.1111111111111111

In [7]:
z

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [9]:
np.ones_like(z).size

10

In [10]:
np.ones(nz).size

10

In [33]:
from scipy.interpolate import RegularGridInterpolator
import numpy as np

def f(x, y, z):
    return 2 * x**3 + 3 * y**2 - z

x = np.linspace(0, 4, 11)
y = np.linspace(4, 9, 22)
z = np.linspace(7, 12, 33)
xg, yg ,zg = np.meshgrid(x, y, z, indexing='ij', sparse=True)
data = f(xg, yg, zg)

In [34]:
interp = RegularGridInterpolator((x, y, z), data)
X = np.arange(4)
Y = np.arange(4, 8)
Z = np.arange(7, 11)

In [35]:
pts = np.column_stack((X, Y, Z))
pts

array([[ 0,  4,  7],
       [ 1,  5,  8],
       [ 2,  6,  9],
       [ 3,  7, 10]])

In [36]:
# pts = np.array([[2.1, 6.2, 8.3], [3.3, 5.2, 7.1]])
interp(pts)

array([ 41.        ,  69.26721088, 115.04081633, 191.76081633])

In [1]:
# importing the module
import json
# Opening JSON file
with open(r'C:\Users\Satellite\Documents\Visualizer\DataVisualizer\data\json\S14-SAFT-MILA2020.json') as json_file:
    data = json.load(json_file)

In [29]:
data.keys()

dict_keys(['fileName', 'fluid', 'coord_label', 'coord_unit', 'prop_label', 'prop_unit', 'GOR', 'P', 'T', 'prop_table'])

In [3]:
data["prop_label"].index('dens_V')

10

In [41]:
np.arange(len(data['prop_label']))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38])

In [10]:
mylist = data['prop_label']
mylist.index('Ceq')

0

In [10]:
x = np.arange(12)
x = np.where(x < 6, x, 0)

In [11]:
x

array([0, 1, 2, 3, 4, 5, 0, 0, 0, 0, 0, 0])

In [12]:
a = 1
b = 2
c = 4
print(a/b/c, (a/b)/c, a/(b/c), a/(b*c))

0.125 0.125 2.0 0.125


In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

abc = np.stack((a,b,c), axis=0)
a1 = abc[0]

print(abc)
print(a)
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[1 2 3]


In [4]:
class Myobject():

    def __init__(self, a, b, c):
        self.a = a
        self.b = b
        self.c = c

In [5]:
someobject = Myobject(1, 2, 3)
someobject.a

1

In [13]:
x = np.arange(5)
y = np.arange(5)
z = np.arange(5)
XYZ = [x, y, z]
stack = np.column_stack(XYZ)
stack

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [19]:
np.sum(stack, axis=1)

array([ 0,  3,  6,  9, 12])

In [17]:
A = np.ones(5)
A_stack = A.reshape(A.size, 1)
stack/A_stack

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

In [20]:
class fluid(object):

    def __init__(self, T):
        self.T = T

myfluid = fluid(100)
myfluid.T

100

In [21]:
myfluid.P = 2000

In [22]:
myfluid.P

2000

In [3]:
import numpy as np
A = np.arange(15).reshape((5, 3))
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [8]:
A[:, :2]

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13]])

In [4]:
np.sum(A, axis=1)

array([ 3, 12, 21, 30, 39])

In [1]:
import numpy as np
from ADEPT_python import pipe, sim, depo
mypipe = pipe(5438.59, 0.05931)
mysim = sim(8640000, 10.2584, True)
mix_phase = ["volume", "volume", "sum"]
TLUT_json = ""
KLUT_dict = {
    "kP_param": [0.360827, 41.12422],
    "kP_model": "t-sp",
    "kAg_param": 0.001871,
    "kAg_model": "default",
    "kD": 0.03,
    "kD_scale": "wb",
    "SR_param": [5, 0.6, 0.16],
    "SR_model": "default"
}
mydepo = depo(mypipe, mysim, TLUT_json, KLUT_dict, mix_phase)

AttributeError: 'str' object has no attribute 'read'

$$t' = \frac{L}{\langle v_z \rangle}t$$
$$\frac{\partial C_f}{\partial t} = \frac{\partial C_f}{\partial t'}\frac{\partial t'}{\partial t} = \frac{L}{\langle v_z \rangle}\frac{\partial C_f}{\partial t'}$$