In [1]:
# import packages
import numpy as np

In [12]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

abc = np.stack((a,b,c), axis=0)
a1 = abc[0]

print(abc)
print(a)
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[1 2 3]
